-- Run this in the Supabase SQL editor after creating your project.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  telegram_username text,
  access_status text not null default 'evaluation_required',
  recommended_profile text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  category text not null check (category in ('ea','indicator','copy_profile')),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  license_key text,
  status text not null default 'pending',
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, product_id)
);

alter table public.profiles enable row level security;
alter table public.user_products enable row level security;
alter table public.products enable row level security;

create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can view own products" on public.user_products for select using (auth.uid() = user_id);
create policy "Public can view active products" on public.products for select using (is_active = true);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

insert into public.products (slug,name,category,description) values
('alpha','Gencouv Alpha','copy_profile','Higher-growth broker-connected copy profile.'),
('core','Gencouv Core','copy_profile','Conservative broker-connected copy profile.'),
('meff-ai','Gencouv Meff AI','ea','Quantum algorithmic expert advisor.'),
('precision-indicators','Precision Indicators','indicator','Professional decision-support indicators.')
on conflict (slug) do nothing;
