import type { LicensePlan } from "./products";
export type PerformanceMetric={label:string;value:string;tone?:"risk"|"default"};
export type ProductDetail={slug:string;name:string;version:string;eyebrow:string;tagline:string;description:string;price:string;mark:string;image?:string;plans?:LicensePlan[];overview:string[];specs:{label:string;value:string}[];metrics:PerformanceMetric[];performanceTitle:string;performanceNote:string;testContext:string;riskTitle:string;riskBody:string;requirements:string[];updates:string[]};

export const productDetails:Record<string,ProductDetail>={
 "lorc-gold-miner":{slug:"lorc-gold-miner",name:"L.O.R.C Gold Miner",version:"",eyebrow:"GENCOUV DEVELOPED / EXPERT ADVISOR / MT5",tagline:"Selective execution. Adaptive recovery. Built for XAUUSD.",description:"A Gencouv-developed automated trading system designed to prioritize qualifying conditions over constant market activity, with structured risk and recovery logic built into execution.",price:"From $1,000",mark:"L",image:"/marketplace/lorc-gold-miner.png",
 plans:[{name:"L.O.R.C Gold",price:"$1,000",cadence:"/ year",summary:"Focused access for traders deploying L.O.R.C on Gold.",features:["1-year L.O.R.C EA access","Gold / XAUUSD configuration files","Gold set-file updates during license","EA updates during license","Standard support"]},{name:"L.O.R.C Full Access",price:"$5,000",summary:"Long-term access to the complete Gencouv L.O.R.C research and configuration ecosystem.",features:["Lifetime L.O.R.C EA access","Gencouv-tested configurations for supported instruments","Continuous configuration releases as market conditions evolve","Lifetime EA updates","Dedicated priority support","Future optimization releases"],featured:true}],
 overview:["L.O.R.C is designed around selective entries rather than constant trading. Its architecture combines qualifying entry conditions, controlled exposure and a structured recovery framework intended to manage losing sequences without treating trade frequency as the objective.","The product is still being evaluated. Backtest and demo forward-test material can document how the system behaved under specific conditions, but neither should be interpreted as an expected return or guarantee of recovery."],
 specs:[{label:"Platform",value:"MetaTrader 5"},{label:"Primary market",value:"Gold / XAUUSD"},{label:"Execution profile",value:"Selective"},{label:"Risk architecture",value:"Structured / configurable"},{label:"Recovery",value:"Adaptive recovery logic"},{label:"Developer",value:"Gencouv Trading Technology"}],
 metrics:[{label:"Forward-test account",value:"$10,000"},{label:"Net gain shown",value:"$784.96"},{label:"Return shown",value:"+7.85%"},{label:"Trades shown",value:"4"},{label:"Winners / losses",value:"2 / 2"},{label:"Evidence status",value:"Demo forward test"}],
 performanceTitle:"Evidence first. Spectacle second.",performanceNote:"The current forward sample is a D-trial/demo account and contains only four shown trades. It is useful as an execution sample, not as evidence of recurring returns.",testContext:"Demo forward-test screenshot · starting balance $10,000 · current balance $10,784.96 · net gain $784.96 · 4 shown XAUUSD trades · 2 winners / 2 losses. Historical backtest results are evaluated separately.",
 riskTitle:"Recovery logic is not immunity from loss.",riskBody:"A recovery framework can increase exposure during adverse sequences depending on configuration. Its quality should be judged using maximum equity drawdown, recovery depth, losing sequences, exposure concentration, slippage sensitivity and out-of-sample behavior, not return alone.",requirements:["MetaTrader 5","Compatible Gold / XAUUSD symbol","Review broker execution and symbol specification","Use a Gencouv-tested configuration appropriate to the supported instrument","Understand risk and recovery settings before activation"],updates:["Gencouv-developed system","Current status: forward testing","Gold configurations are the primary release focus","Additional supported-instrument configurations are released only after Gencouv testing"]},
 "quantum-queen":{slug:"quantum-queen",name:"Quantum Queen",version:"v3.52",eyebrow:"EXPERT ADVISOR / MT5",tagline:"Gold automation, presented with the evidence attached.",description:"An XAUUSD automated trading system for MetaTrader 5, presented with supplied configuration and MT5 Strategy Tester evidence rather than invented performance claims.",price:"$2,000",mark:"Q",overview:["The supplied EA configuration identifies Quantum Queen MT5 v3.52 as an XAUUSD system and states that chart timeframe does not matter because the EA manages its timeframe internally.","The configuration includes automatic or fixed-lot controls, spread and slippage parameters, strategy-set selection and an on-chart control panel. Configuration facts and historical test results are deliberately kept separate."],specs:[{label:"Platform",value:"MetaTrader 5"},{label:"Market",value:"Gold / XAUUSD"},{label:"Version",value:"3.52"},{label:"Fixed lot in supplied test",value:"0.01"},{label:"Fixed balance reference",value:"$500"},{label:"Magic number",value:"1234"}],metrics:[{label:"Initial deposit",value:"$1,000"},{label:"Net profit",value:"$4,398.67"},{label:"Profit factor",value:"7.81"},{label:"Profitable trades",value:"80.29%"},{label:"Max balance DD",value:"3.75%"},{label:"Relative equity DD",value:"47.29%",tone:"risk"}],performanceTitle:"What the supplied MT5 report actually shows.",performanceNote:"Historical simulation, not a live account record and not a forecast. Profit and drawdown belong in the same conversation.",testContext:"MT5 Strategy Tester · XAUUSDz · M15 · 1 Jan 2026 to 20 Apr 2026 · Exness Technologies Ltd · USD account · 1:100 leverage · 98% history quality · 208 trades.",riskTitle:"The equity drawdown matters.",riskBody:"The supplied test recorded 47.29% relative equity drawdown despite a much smaller 3.75% maximal balance drawdown. Backtests can differ substantially from live execution because of spreads, slippage, latency, broker conditions, symbol specifications, market regime and configuration.",requirements:["MetaTrader 5","Gold / XAUUSD symbol compatibility","Review broker symbol specification before deployment","Understand lot and risk configuration before activation"],updates:["Current marketplace version: 3.52","Configuration evidence documented on product page","Future releases and compatibility notes will be recorded here"]}
};
