import Image from 'next/image';
import Link from 'next/link';
import Countdown from '@/components/Countdown';
import { ArrowUpRight, Bot, BrainCircuit, Check, LockKeyhole, ShieldCheck, Sparkles, TimerReset } from 'lucide-react';

const TELEGRAM='https://t.me/Gencou_bot';
const reviews=[
 {src:'/assets/review-chuks-1.jpeg', quote:'Profit the past two weeks: $918. I have withdrawn a total of $1,500.', tag:'Withdrawal proof'},
 {src:'/assets/review-stacy.jpeg', quote:'Started copying this month and already up by more than 50%.', tag:'Copy client'},
 {src:'/assets/review-johnson.jpeg', quote:'I started with curiosity, but I am glad I took action.', tag:'Automated execution'},
 {src:'/assets/review-harry.jpeg', quote:'Seeing my money work for me really is a relief.', tag:'Client experience'},
 {src:'/assets/review-martin.jpeg', quote:'Cheers to more profits.', tag:'Trading history'},
];

export default function Home(){return <main>
  <div className="noise"/>
  <header className="site-header"><a href="#top" className="logo-lockup"><Image src="/assets/gencouv-logo-white.png" alt="Gencouv" width={36} height={36}/><b>GENCOUV</b></a><nav><a href="#copy">Copy trading</a><a href="#products">Technology</a><a href="#proof">Proof</a><a href="#faq">FAQ</a></nav><div className="header-actions"><Link href="/login" className="text-link">Client login</Link><a className="button small" href={`${TELEGRAM}?start=general`}>Ask Gencouv AI</a></div></header>

  <section id="top" className="hero section"><div className="hero-copy"><div className="availability"><i/> Private intake open · Limited approvals</div><h1>Trading technology<br/><span>built without limits.</span></h1><p>Broker-connected copy trading, expert advisors and professional indicators engineered for systematic execution.</p><div className="hero-actions"><a className="button primary" href={`${TELEGRAM}?start=evaluation`}>Request private access <ArrowUpRight size={17}/></a><a className="button ghost" href="#products">Explore the technology</a></div><div className="trust-line"><ShieldCheck size={18}/> We never take custody of client funds.</div></div><div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core"><Image src="/assets/gencouv-logo-white.png" alt="Gencouv mark" width={150} height={150}/><span>ALGORITHMIC<br/>EXECUTION CORE</span></div><div className="data-card dc1"><span>Automation</span><b>ACTIVE</b></div><div className="data-card dc2"><span>Broker link</span><b>SECURE</b></div><div className="data-card dc3"><span>Execution</span><b>RULE-BASED</b></div></div></section>

  <section className="intake section"><div><span className="eyebrow">Current private intake</span><h2>Access is evaluated,<br/>not simply purchased.</h2><p>Our Telegram assistant screens every applicant for suitability, risk understanding and product fit before access is granted.</p><div className="capacity"><span><b>17</b> approved</span><span><b>8</b> spaces under review</span><span><b>25</b> maximum intake</span></div></div><div className="intake-card"><div className="intake-head"><TimerReset/><span>Applications close in</span></div><Countdown/><a className="button primary wide" href={`${TELEGRAM}?start=evaluation`}>Begin evaluation</a><small>Capacity numbers should be updated to match the real intake.</small></div></section>

  <section id="copy" className="section"><div className="section-heading"><span className="eyebrow">Broker-connected automation</span><h2>Two profiles. One disciplined infrastructure.</h2><p>Your money remains in your own supported broker account. Gencouv provides the automated execution layer.</p></div><div className="profiles"><article className="profile-card alpha"><div className="card-top"><span>01 / HIGH GROWTH</span><b>ALPHA</b></div><div className="metric"><strong>190%+</strong><span>historical return since May 2026</span></div><div className="metric smallmetric"><strong>30%</strong><span>maximum historical drawdown</span></div><ul><li><Check/> Fully automated execution</li><li><Check/> Designed for higher risk tolerance</li><li><Check/> Broker-connected, non-custodial</li></ul><a href={`${TELEGRAM}?start=alpha`} className="button primary wide">Begin Alpha evaluation</a></article><article className="profile-card core-profile"><div className="card-top"><span>02 / CONSERVATIVE</span><b>CORE</b></div><div className="metric"><strong>60%+</strong><span>historical return since May 2026</span></div><div className="metric smallmetric"><strong>15%</strong><span>maximum historical drawdown</span></div><ul><li><Check/> Lower historical drawdown</li><li><Check/> Balanced automation profile</li><li><Check/> Broker-connected, non-custodial</li></ul><a href={`${TELEGRAM}?start=core`} className="button ghost wide">Begin Core evaluation</a></article></div><p className="risk-note">Historical figures are not guarantees of future performance. Trading involves substantial risk, including loss of capital.</p></section>

  <section id="products" className="section technology"><div className="section-heading"><span className="eyebrow">Gencouv technology stack</span><h2>Systems over guesswork.</h2></div><div className="tech-grid"><article className="tech-card large"><div className="tech-icon"><Bot/></div><span className="eyebrow">Expert Advisor</span><h3>Gencouv Meff AI</h3><p>Quantum algorithmic EA built for automated market execution with structured risk controls and continuous system monitoring.</p><div className="tech-visual"><div className="wire-sphere"/><div className="pulse-line"/></div><a className="text-link" href={`${TELEGRAM}?start=meff_ai`}>Get access to EA <ArrowUpRight size={16}/></a></article><article className="tech-card"><div className="tech-icon"><BrainCircuit/></div><span className="eyebrow">Professional indicators</span><h3>Precision market tools</h3><p>Decision-support indicators created to help traders map structure, momentum and execution zones with greater clarity.</p><a className="text-link" href={`${TELEGRAM}?start=indicators`}>Get access to indicators <ArrowUpRight size={16}/></a></article><article className="tech-card"><div className="tech-icon"><Sparkles/></div><span className="eyebrow">Copy infrastructure</span><h3>Automated participation</h3><p>Connect an approved broker account and let the system copy executions automatically, while you retain account control.</p><a className="text-link" href={`${TELEGRAM}?start=copy_trading`}>Evaluate my suitability <ArrowUpRight size={16}/></a></article></div></section>

  <section className="custody section"><div className="lock"><LockKeyhole/></div><span className="eyebrow">Designed around control</span><h2>Your capital never enters a Gencouv wallet.</h2><p>We do not accept investment deposits. You fund and control your own account with a supported broker. Once approved and connected, the AI system places trades directly on that broker account.</p><div className="flow"><span>YOU</span><i/><span>YOUR BROKER</span><i/><span>GENCOUV AUTOMATION</span><i/><span>TRADES EXECUTED</span></div></section>

  <section className="section performance"><div className="section-heading"><span className="eyebrow">System evidence</span><h2>Performance presented with context.</h2><p>Original account evidence remains available beside the redesigned metrics, because polished interfaces are lovely but proof still has to exist.</p></div><div className="performance-grid"><article className="performance-panel"><div className="performance-head"><div><span>Gencouv Meff AI</span><small>Since May 2026</small></div><span className="status-pill"><i/> System active</span></div><div className="big-number">195.20%</div><span>recorded ROI shown in supplied activity proof</span><div className="stat-row"><div><b>38 min</b><span>Avg. holding time</span></div><div><b>37.2</b><span>Trades per week</span></div><div><b>30 days</b><span>ROI view</span></div></div></article><article className="proof-images"><Image src="/assets/performance-overview.jpeg" alt="Gencouv Meff AI performance overview" width={600} height={600}/><Image src="/assets/performance-details.jpeg" alt="Gencouv Meff AI activity details" width={600} height={800}/></article></div></section>

  <section id="proof" className="section reviews"><div className="section-heading"><span className="eyebrow">Real client experiences</span><h2>Conversations, withdrawals and account history.</h2><p>Client identities should be shown only with permission. The production version can blur names and profile photographs where needed.</p></div><div className="review-track">{reviews.map(r=><article className="review-card" key={r.src}><div className="review-image"><Image src={r.src} alt="Client review screenshot" fill sizes="(max-width: 800px) 85vw, 320px"/></div><span>{r.tag}</span><blockquote>“{r.quote}”</blockquote></article>)}</div></section>

  <section className="section brand-world"><div className="brand-copy"><span className="eyebrow">One visual language</span><h2>Built to feel like financial infrastructure.</h2><p>Monochrome identity, metallic depth, controlled motion and confident spacing. No rented supercars. Society survives another day.</p><a className="button ghost" href={`${TELEGRAM}?start=brand`}>Speak with Gencouv AI</a></div><div className="brand-gallery"><Image src="/assets/gencouv-brand-cover.jpeg" alt="Gencouv brand cover" width={600} height={600}/><Image src="/assets/gencouv-shirt.jpeg" alt="Gencouv apparel" width={600} height={600}/><Image src="/assets/gencouv-signage.jpeg" alt="Gencouv signage" width={600} height={600}/></div></section>

  <section id="faq" className="section faq"><div><span className="eyebrow">Frequently asked</span><h2>Important answers before access.</h2><a className="button ghost" href={`${TELEGRAM}?start=faq`}>Ask Gencouv AI</a></div><div className="faq-list">{[
 ['Does Gencouv collect investment funds?','No. Gencouv does not take custody of client capital. Approved clients fund and control their own supported broker accounts.'],
 ['How do I access Alpha or Core?','Begin the Telegram evaluation. The assistant reviews your objectives, experience and risk tolerance before recommending a profile.'],
 ['Can I buy an EA directly?','Use “Get access to EA.” The Telegram assistant will explain compatibility, pricing, delivery and setup support.'],
 ['Are returns guaranteed?','No. All performance figures are historical. Trading carries risk and future results can differ materially.'],
 ['Where do I get support?','The Gencouv Telegram assistant handles inquiries, onboarding and escalation to a human team member when required.']
 ].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>

  <section className="section final-cta"><Image src="/assets/gencouv-logo-white.png" alt="Gencouv" width={72} height={72}/><span className="eyebrow">Private access</span><h2>Access to Gencouv begins<br/>with an evaluation.</h2><p>Discover the profile or product suited to your needs through our Telegram onboarding assistant.</p><div><a className="button primary" href={`${TELEGRAM}?start=evaluation`}>Begin evaluation <ArrowUpRight size={17}/></a><Link className="button ghost" href="/signup">Create client account</Link></div></section>

  <footer><div><a href="#top" className="logo-lockup"><Image src="/assets/gencouv-logo-white.png" alt="Gencouv" width={32} height={32}/><b>GENCOUV</b></a><p>Automated trading technology.</p></div><div><b>Products</b><a href="#copy">Copy trading</a><a href="#products">Expert advisors</a><a href="#products">Indicators</a></div><div><b>Access</b><a href={`${TELEGRAM}?start=general`}>Telegram assistant</a><Link href="/login">Client login</Link><a href="mailto:support@gencouv.com">support@gencouv.com</a></div><div><b>Legal</b><a href="#risk">Risk disclosure</a><a href="#">Privacy</a><a href="#">Terms</a></div><small>© 2026 Gencouv. Past performance does not guarantee future results.</small></footer>
  <a className="floating-chat" href={`${TELEGRAM}?start=floating_chat`}><span><Bot size={19}/></span> Ask Gencouv AI</a>
</main>}
