import FloatingGencouvChat from "@/components/FloatingGencouvChat";

const telegram = "https://t.me/GENCOUV";

export default function QuantumQueenProductPage(){
 return <main>
  <nav className="nav shell"><a className="brand" href="/"><span>G</span><div><b>GENCOUV</b><small>AI TRADING TECHNOLOGY</small></div></a><div className="links"><a href="/marketplace">Marketplace</a><a href="/risk-disclosure">Risk Disclosure</a></div><a className="navCta" href="/checkout/quantum-queen">Buy Now · $2,000</a></nav>
  <section className="productHero shell"><div className="productArt"><div className="q">Q</div><span>QUANTUM QUEEN</span><small>MT5 EA · VERSION 3.52</small></div><div className="heroCopy"><div className="eyebrow left">EXPERT ADVISOR · MT5</div><h1>Quantum Queen</h1><p className="lead">An XAUUSD automated trading system for MetaTrader 5, presented with the supplied configuration and MT5 Strategy Tester evidence rather than invented performance folklore.</p><div className="price">$2,000</div><div className="heroActions"><a className="primary" href="/checkout/quantum-queen">Purchase Quantum Queen</a><a className="secondary" href={telegram} target="_blank" rel="noreferrer">Ask Gencouv ↗</a></div></div></section>

  <section className="metrics shell"><div><span>TESTED SYMBOL</span><strong>XAUUSDz</strong></div><div><span>TEST PERIOD</span><strong>Jan–Apr 2026</strong></div><div><span>TOTAL TRADES</span><strong>208</strong></div><div><span>HISTORY QUALITY</span><strong>98%</strong></div></section>

  <section className="section shell split"><div><div className="eyebrow left">THE SYSTEM</div><h2>Built for Gold. Managed internally.</h2><p>The supplied EA configuration identifies Quantum Queen MT5 v3.52 as an XAUUSD system and states that chart timeframe does not matter because the EA manages its timeframe internally. The configuration includes automatic or fixed-lot controls, spread and slippage parameters, strategy-set selection and an on-chart control panel.</p><p>This page deliberately distinguishes configuration facts from backtest results. A strategy tester can tell you how a configuration behaved against historical test data. It cannot tell you what your next month of live trading will look like.</p></div><aside className="spec"><h3>Configuration snapshot</h3><span><b>Platform</b>MetaTrader 5</span><span><b>Market</b>Gold / XAUUSD</span><span><b>Version</b>3.52</span><span><b>Fixed lot setting in supplied test</b>0.01</span><span><b>Fixed balance reference</b>$500</span><span><b>Magic number</b>1234</span></aside></section>

  <section className="band"><div className="shell"><div className="sectionHead"><div><div className="eyebrow left">SUPPLIED BACKTEST</div><h2>What the MT5 report actually shows.</h2></div><p>These numbers come from the supplied Strategy Tester report. They are historical simulation results, not a live account record and not a guarantee.</p></div><div className="resultGrid"><div><span>Initial deposit</span><strong>$1,000</strong></div><div><span>Net profit</span><strong>$4,398.67</strong></div><div><span>Profit factor</span><strong>7.81</strong></div><div><span>Profitable trades</span><strong>80.29%</strong></div><div><span>Max balance DD</span><strong>3.75%</strong></div><div className="riskMetric"><span>Relative equity DD</span><strong>47.29%</strong></div></div><div className="reportNote"><b>Test context</b><p>MT5 Strategy Tester · XAUUSDz · M15 · 1 Jan 2026 to 20 Apr 2026 · Exness Technologies Ltd · USD account · 1:100 leverage · 98% history quality · 208 trades.</p></div></div></section>

  <section className="section shell"><div className="sectionHead"><div><div className="eyebrow left">READ THE RISK, NOT JUST THE PROFIT</div><h2>The equity drawdown matters.</h2></div><p>The supplied test recorded 47.29% relative equity drawdown, despite a much smaller 3.75% maximal balance drawdown. That distinction belongs prominently on a serious product page rather than buried under a shiny return number.</p></div><div className="riskBox"><b>Performance & risk notice</b><p>Backtests are hypothetical and can differ substantially from live execution because of spreads, slippage, latency, broker conditions, symbol specifications, market regime and configuration. Automated trading can produce substantial losses. Purchase of software does not include any guarantee of profitability. Review the <a href="/risk-disclosure">full Risk Disclosure</a> before purchasing.</p></div></section>

  <section className="finalCta shell"><div className="eyebrow">QUANTUM QUEEN · MT5 EA v3.52</div><h2>Review it. Understand the risk. Then decide.</h2><p>Digital trading software · $2,000</p><div className="heroActions"><a className="primary" href="/checkout/quantum-queen">Buy Quantum Queen · $2,000</a><a className="secondary" href={telegram} target="_blank" rel="noreferrer">Talk to Gencouv ↗</a></div></section><FloatingGencouvChat />
  <style>{`.productHero{display:grid;grid-template-columns:.9fr 1.1fr;gap:70px;align-items:center;padding:100px 0 80px}.productArt{aspect-ratio:1;display:flex;flex-direction:column;align-items:center;justify-content:center;border:1px solid rgba(53,228,192,.2);border-radius:32px;background:radial-gradient(circle,rgba(53,228,192,.18),transparent 48%),linear-gradient(145deg,#061617,#010506);box-shadow:0 35px 100px rgba(0,0,0,.3)}.q{width:190px;height:190px;display:grid;place-items:center;border:2px solid #35e4c0;border-radius:44px;transform:rotate(45deg);font-size:120px;font-weight:950;color:#35e4c0;line-height:1;text-shadow:0 0 30px rgba(53,228,192,.35);margin-bottom:55px}.q::first-letter{transform:rotate(-45deg)}.productArt>span{font-size:24px;font-weight:900;letter-spacing:.12em}.productArt small{margin-top:8px;color:#6f8a84;letter-spacing:.2em}.heroCopy h1{font-size:clamp(64px,9vw,112px);line-height:.84;letter-spacing:-.07em;margin:18px 0 28px}.lead{font-size:18px;line-height:1.75;color:#aebfbc}.price{font-size:58px;font-weight:950;margin:30px 0}.heroActions{display:flex;gap:10px;flex-wrap:wrap}.metrics,.resultGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.metrics{padding-bottom:80px}.metrics>div,.resultGrid>div{padding:22px;border:1px solid rgba(255,255,255,.08);border-radius:16px}.metrics span,.resultGrid span{display:block;color:#738783;font-size:10px;letter-spacing:.13em}.metrics strong,.resultGrid strong{display:block;margin-top:8px;font-size:22px}.split{display:grid;grid-template-columns:1.3fr .7fr;gap:60px}.split h2{font-size:clamp(42px,6vw,72px);line-height:.95;letter-spacing:-.05em}.split p{color:#9fb0ad;line-height:1.8}.spec{padding:28px;border:1px solid rgba(53,228,192,.16);border-radius:22px}.spec h3{margin-top:0}.spec span{display:block;padding:13px 0;border-bottom:1px solid rgba(255,255,255,.07);color:#a9b8b5}.spec b{display:block;color:#607b75;font-size:9px;letter-spacing:.12em;text-transform:uppercase;margin-bottom:4px}.band{padding:90px 0;background:rgba(53,228,192,.035);border-top:1px solid rgba(53,228,192,.1);border-bottom:1px solid rgba(53,228,192,.1)}.resultGrid{grid-template-columns:repeat(3,1fr);margin-top:40px}.resultGrid strong{font-size:34px}.riskMetric{border-color:rgba(255,180,90,.3)!important}.riskMetric strong{color:#ffc37a}.reportNote,.riskBox{margin-top:20px;padding:22px;border-left:2px solid #35e4c0;background:rgba(53,228,192,.04)}.reportNote p,.riskBox p{color:#8fa09d;line-height:1.7;margin-bottom:0}.riskBox a{color:#35e4c0}@media(max-width:850px){.productHero,.split{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}.resultGrid{grid-template-columns:1fr 1fr}.productHero{gap:38px}.productArt{max-width:560px;width:100%;margin:auto}}@media(max-width:600px){.metrics,.resultGrid{grid-template-columns:1fr}.productHero{padding-top:60px}.heroCopy h1{font-size:62px}.productArt>span{font-size:17px}.q{width:130px;height:130px;font-size:80px;margin-bottom:42px}}`}</style>
 </main>
}
