import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase-server";

function formatDate(value:string|null){if(!value)return "Lifetime";return new Intl.DateTimeFormat("en",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value));}
function productName(slug:string){if(slug==="lorc-gold-miner")return "L.O.R.C Gold Miner";if(slug==="quantum-queen")return "Quantum Queen";if(slug==="sixtynine")return "SixtyNine EA";return slug.replaceAll("-"," ");}

export default async function Dashboard(){
 const supabase=await createClient();
 const {data:{user}}=await supabase.auth.getUser();
 if(!user)redirect("/login?next=/dashboard");
 const [{data:profile},{data:entitlements},{data:orders}]=await Promise.all([
  supabase.from("profiles").select("access_status").eq("id",user.id).maybeSingle(),
  supabase.from("marketplace_entitlements").select("id,product_slug,license_tier,status,starts_at,expires_at,order_id").eq("user_id",user.id).order("created_at",{ascending:false}),
  supabase.from("marketplace_orders").select("order_id,product_slug,license_tier,payment_status,price_amount,price_currency,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(6)
 ]);
 const active=(entitlements||[]).filter(x=>x.status==="active"&&(!x.expires_at||new Date(x.expires_at)>new Date()));
 const cards=[
  ["Access status",profile?.access_status?.replaceAll("_"," ")||"Evaluation required","Portfolio-management access is reviewed separately from Trading Bots purchases."],
  ["Portfolio status","Not connected","Your managed-strategy participation status will appear here after approval."],
  ["Trading Bots",`${active.length} active license${active.length===1?"":"s"}`,"Your purchased trading technology and license status."],
  ["Support","Available","Contact Gencouv Support for account, onboarding or product questions."]
 ];
 return <main className="dashboard-shell"><aside><Link href="/" className="brand">GENCOUV</Link><nav><a className="active" href="#overview">Overview</a><a href="#portfolio">Portfolio</a><a href="#library">Trading Bots Library</a><a href="#orders">Orders</a><a href="https://t.me/Gencou_bot?start=dashboard">Support</a></nav><a className="button ghost wide" href="https://t.me/Gencou_bot?start=dashboard">Contact Gencouv Support</a></aside><section className="dashboard-main" id="overview"><header><div><span className="eyebrow">Client command centre</span><h1>Dashboard</h1></div><span className="status-pill"><i/> Systems operational</span></header><div className="dashboard-grid">{cards.map(([a,b,c])=><article className="dash-card" key={a}><span>{a}</span><strong>{b}</strong><p>{c}</p></article>)}</div>
 <section id="library" className="dash-panel libraryPanel"><div className="panelHead"><div><span className="eyebrow">Trading Bots library</span><h2>Your trading technology.</h2><p>Only products attached to active Trading Bots entitlements appear here. Portfolio-management approval does not control EA ownership.</p></div><Link className="button ghost" href="/marketplace">Browse Trading Bots</Link></div>
 {active.length?<div className="licenseGrid">{active.map(item=><article className="licenseCard" key={item.id}><div><span className="eyebrow">{item.license_tier.toUpperCase()} LICENSE</span><h3>{productName(item.product_slug)}</h3></div><div className="licenseMeta"><span>Status<strong>Active</strong></span><span>Access<strong>{item.expires_at?`Until ${formatDate(item.expires_at)}`:"Lifetime"}</strong></span></div><p>{item.product_slug==="lorc-gold-miner"&&item.license_tier==="gold"?"Gold/XAUUSD configurations and eligible updates during the active license period.":item.product_slug==="lorc-gold-miner"&&item.license_tier==="full"?"Full L.O.R.C ecosystem access across supported Gencouv-tested configurations and future eligible releases.":"Trading Bot access attached to this account."}</p><div className="licenseActions"><Link className="button primary" href={`/dashboard/marketplace/${item.product_slug}`}>Open product</Link><span>Order {item.order_id}</span></div></article>)}</div>:<div className="emptyLibrary"><strong>No active Trading Bot licenses yet.</strong><p>Products will appear here automatically after a verified purchase is fulfilled.</p></div>}</section>
 <section id="orders" className="dash-panel ordersPanel"><div><span className="eyebrow">Recent Trading Bot orders</span><h2>Payment & fulfillment history.</h2></div>{orders?.length?<div className="orderList">{orders.map(order=><div className="orderRow" key={order.order_id}><div><strong>{productName(order.product_slug)}</strong><span>{order.license_tier} · {new Intl.NumberFormat("en-US",{style:"currency",currency:String(order.price_currency||"usd").toUpperCase(),maximumFractionDigits:0}).format(Number(order.price_amount))}</span></div><div><span className={`orderStatus ${order.payment_status}`}>{order.payment_status.replaceAll("_"," ")}</span><small>{formatDate(order.created_at)}</small></div></div>)}</div>:<p className="muted">No Trading Bot orders recorded for this account.</p>}</section>
 <section id="portfolio" className="dash-panel"><div><span className="eyebrow">Next action</span><h2>Complete your portfolio-management evaluation.</h2><p>Gencouv reviews objectives, investment and trading experience, risk tolerance, jurisdiction and applicable onboarding requirements before participation is considered. Approval is not guaranteed.</p></div><a className="button primary" href="https://t.me/Gencou_bot?start=evaluation">Begin evaluation</a></section></section>
 <style>{`.libraryPanel,.ordersPanel{display:block}.panelHead{display:flex;justify-content:space-between;gap:35px;align-items:end}.panelHead p{max-width:680px}.licenseGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:32px}.licenseCard{padding:25px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.018)}.licenseCard h3{font-size:25px;margin:9px 0 24px}.licenseMeta{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid rgba(255,255,255,.07);border-bottom:1px solid rgba(255,255,255,.07);padding:14px 0}.licenseMeta span{font-size:9px;color:#6f817d}.licenseMeta strong{display:block;color:#c7d3d0;font-size:11px;margin-top:6px}.licenseCard p{color:#82938f;font-size:12px;line-height:1.65;min-height:58px}.licenseActions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:20px}.licenseActions>span{font-size:7px;color:#52635f;max-width:48%;overflow:hidden;text-overflow:ellipsis}.emptyLibrary{padding:34px;margin-top:28px;border:1px dashed rgba(255,255,255,.12);color:#80928d}.emptyLibrary strong{color:#c8d4d1}.orderList{margin-top:26px;border-top:1px solid rgba(255,255,255,.08)}.orderRow{display:flex;justify-content:space-between;gap:25px;padding:17px 0;border-bottom:1px solid rgba(255,255,255,.07)}.orderRow strong,.orderRow span{display:block}.orderRow>div>span,.orderRow small{color:#71847f;font-size:9px;margin-top:5px}.orderRow>div:last-child{text-align:right}.orderStatus{display:inline-block!important;text-transform:uppercase;letter-spacing:.1em;font-size:8px!important;color:#9dafaa!important}.orderStatus.finished{color:#35e4c0!important}.muted{color:#71847f}@media(max-width:850px){.panelHead{display:block}.panelHead .button{display:inline-block;margin-top:20px}.licenseGrid{grid-template-columns:1fr}}`}</style></main>;
}
